name: 'latest-release'
description: 'Retrieves the latest release (tag) of a repository'
author: 'Ralf Stuckert'
inputs:
  repository:
    required: false
    description: 'the repository to get the latest release from'
    default: ${{ github.repository }}
  token:
    required: false
    description: 'the PAT allowing to access the repository'
    default: ${{ github.token }}
  failOnMissingRelease:
    required: false
    description: 'indicates if the action should fail, if there is no release. Default is true'
    default: 'true'
outputs:
  release:
    description: 'the release version tag'
  name:
    description: 'the release name'
  description:
    description: 'the release description'
runs:
  using: 'node12'
  main: 'dist/index.js'
