name: 'latest-release'
description: 'Retrieves the latest release (tag) of a repository'
author: 'Ralf Stuckert'
inputs:
  repository:
    required: true
    description: 'the repository to get the latest release from'
  token:
    required: true
    description: 'the PAT allowing to access the repository'
    default: ${{ github.token }}
outputs:
  release:
    description: 'the release version tag'
runs:
  using: 'node12'
  main: 'dist/index.js'
